name: Build, Push e Deploy com Versão Automática
run-name: Build e Push da Imagem Docker e Deploy Automático
description: Build e Push da Imagem Docker e Deploy Automático com base na mudança do arquivo

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set-version.outputs.image_tag }}
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Definir versão a partir da tag
        id: set-version
        run: |
          TAG_NAME="${GITHUB_REF#refs/tags/}"
          echo "IMAGE_TAG=$TAG_NAME" >> $GITHUB_ENV
          echo "image_tag=$TAG_NAME" >> $GITHUB_OUTPUT
          echo "Versão detectada: $TAG_NAME"

      - name: Login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build da imagem Docker
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/hello-app:${{ env.IMAGE_TAG }} .

      - name: Push da imagem para o Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/hello-app:${{ env.IMAGE_TAG }}

  update-manifest:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Clonar repo de manifests via SSH
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.MANIFEST_REPO }}
          path: manifests
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Listar arquivos do diretório manifests
        run: ls -l manifests

      - name: Atualizar arquivo de deployment com nova imagem
        run: |
          sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/hello-app:${{ needs.build-and-push.outputs.image_tag }}|" manifests/manifests/deployment.yaml
          echo "Arquivo de deployment atualizado com a nova imagem."

      - name: Commit e criar Pull Request com nova imagem
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          title: "Atualiza deployment para imagem ${{ env.IMAGE_TAG }}"
          commit-message: "Atualiza imagem para ${{ env.IMAGE_TAG }}"
          base: main
          branch: update-image-${{ needs.build-and-push.outputs.image_tag }}
          path: manifests
